config/routes.rb
  Rails.application.routes.draw do
    root to: 'tasks#index'
    resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to action:'index'
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to action:'index'
  end

  def destroy
    @task.destroy
    redirect_to action:'index'
  end

  private

  def task_params
    params.require(:task).permit(:name, :status)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskmanager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :status %>
  <%= form.text_field :status %>

  <%= form.submit %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit this task</h1>
<br>
<%= link_to 'See all tasks back', '/tasks' %>

<br>
<%=render 'form' %>

app/views/tasks/index.html.erb
<h1>Here are all my tasks</h1>
<br>

<%= link_to 'Create a new task', '/tasks/new' %>
<br>

<ul>
  <% @tasks.each do |task|%>
  <li><%= link_to task.name, task_path(task) %>, <%= task.status%> - <%= link_to 'Edit this task', edit_task_path(task) %> - <%= link_to 'Delete this task', task_path(task), method: :delete, data: { confirm: "Are you sure you want to delete this task?" } %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>
<br>
<%= link_to 'See all tasks back', '/tasks' %>
<br>
<br>
<%=render "form" %>

app/views/tasks/show.html.erb
<h2>Your task</h2>
<br>

<p><bold><%= @task.name %></bold> created <%= @task.created_at %>, and its status is <%= @task.status %></p>
<br>

<%= link_to 'See all tasks back', '/tasks' %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>